on:
  release:
    types: [published]
name: Release
jobs:
  pypi:
    name: PyPI Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Remove docs before release
        run: rm -rf docs/
      - name: Install pre-reqs
        run: |
          python -m pip install setuptools --upgrade
          python -m pip install packaging --upgrade
      - name: Create package
        run: |
          make package
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: $ {{ secrets.PYPI_API_TOKEN }}
          repository-url: https://upload.pypi.org/legacy/
